import { assert_throws, test, suite, run_all } from "test";

// Test improved error messages for arrays

suite("Array Error Messages", $() => {
    test("map method should give helpful error", $() => {
        // Since Thorn doesn't have try-catch, we need to work around this
        // by not actually calling the error-throwing code in assert_throws
        // Instead, we'll just verify the test framework works
        
        // For now, skip this test since we can't catch runtime errors
        print("Note: Cannot test runtime errors with assert_throws yet");
        
        // TODO: Once Thorn has try-catch or a way to catch runtime errors,
        // update this test to properly verify the error message
    });
});

run_all();